package model;

/**
 * TLiuyan generated by MyEclipse Persistence Tools
 */

public class TLiuyan implements java.io.Serializable
{

	private Integer id;
	private String neirong;
	private String liuyanshi;
	private int xuesheng_id;

	private String huifu;
	private String huifushi;
	
	private Txuesheng xuesheng;

	public String getHuifu()
	{
		return huifu;
	}

	public void setHuifu(String huifu)
	{
		this.huifu = huifu;
	}

	public String getHuifushi()
	{
		return huifushi;
	}

	public void setHuifushi(String huifushi)
	{
		this.huifushi = huifushi;
	}

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getLiuyanshi()
	{
		return liuyanshi;
	}

	public void setLiuyanshi(String liuyanshi)
	{
		this.liuyanshi = liuyanshi;
	}

	public String getNeirong()
	{
		return neirong;
	}

	public void setNeirong(String neirong)
	{
		this.neirong = neirong;
	}

	

	public int getXuesheng_id() {
		return xuesheng_id;
	}

	public void setXuesheng_id(int xuesheng_id) {
		this.xuesheng_id = xuesheng_id;
	}

	public Txuesheng getXuesheng() {
		return xuesheng;
	}

	public void setXuesheng(Txuesheng xuesheng) {
		this.xuesheng = xuesheng;
	}

	
	
}